baseURL = '/'
languageCode = 'en-us'
title = 'fd00::1 • "Wall of Text" edition'
theme = 'terminal'
paginate = 5

[params]
    contentTypeName = "content/entries"
    centerTheme = true
    showLastUpdated = true
    enableGitInfo = true
    [params.footer]
        bottomText = "•"
[languages]
    [languages.en]
        languageName = "English"
        title = "fd00::1"
        subtitle = "If the fediverse is not enough…"
    [languages.en.params.logo]
      logoText = "fd00::1"
      logoHomeLink = "/"

    [languages.en.menu]
    #  [[languages.en.menu.main]]
    #    identifier = "about"
    #    name = "About"
    #    url = "/about"